<?php
/**
 * @link http://dragonjsonserver.de/
 * @copyright Copyright (c) 2012-2013 DragonProjects (http://dragonprojects.de/)
 * @license http://license.dragonprojects.de/dragonjsonserver.txt New BSD License
 * @author Christoph Herrmann <developer@dragonprojects.de>
 * @package DragonJsonServerGUI
 */
?>
<?= $this->doctype() ?>
<html lang="de">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle($this->name . ' ' . $this->version)->setSeparator(' - ')->setAutoEscape(false) ?>
        <?= $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
                ->appendStylesheet($this->basePath() . '/css/bootstrap.min.css')
                ->appendStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                ->appendStylesheet($this->basePath() . '/css/style.css') ?>
        <?= $this->headScript()
                ->appendFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', ['conditional' => 'lt IE 9'])
                ->appendFile($this->basePath() . '/js/jquery.min.js')
                ->appendFile($this->basePath() . '/js/bootstrap.min.js')
                ->appendFile($this->basePath() . '/js/dragonjsonserver.client.js')
                ->appendFile($this->basePath() . '/js/dragonjsonserver.request.js')
                ->appendFile($this->basePath() . '/js/URI.js')
                ->appendFile($this->basePath() . '/js/dragonjsonservergui.gui.js') ?>
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="brand" href="<?= $this->url('home') ?>"><?= $this->name . ' ' . $this->version ?></a>
                </div>
            </div>
        </div>
        <div class="container">
            <?= $this->content; ?>
            <hr>
            <footer>
                <p><?= $this->copyright ?></p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
